version: "3.2"
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=testtest # secret key must be minimum 8 or more characters long
    ports:
      - 9000:9000/tcp
    command: server /data